package com.github.kiolk.devto.utils.localisation

object StringsKeys {
    const val DAYS_AGO_SINCE_PUBLICATION = "days_ago_since_publication"
    const val HOURS_AGO_SINCE_PUBLICATION = "hours_ago_since_publication"
    const val MINUTES_AGO_SINCE_PUBLICATION = "minutes_ago_since_publication"
    const val COMMENTS = "comments"
    const val REACTIONS = "reactions"
    const val READING_TIME = "reading_time"
    const val ADD_COMMENT = "add_comment"
    const val READING_ALL_COMMENTS = "reading_all_comments"
    const val RELATED = "related_sorting"
    const val LATEST = "latest_sorting"
    const val TOP = "top_sorting"
    const val TOP_WEEK = "top_week_sorting"
    const val TOP_MONTH = "top_month_sorting"
    const val TOP_YEAR = "top_year_sorting"
    const val TOP_INFINITY = "top_infinity_sorting"
    const val MOST_RELEVANT = "most_relevant"
    const val NEWEST = "newest"
    const val OLDEST = "oldest"
    const val USER = "people"
    const val ARTICLE = "posts"
    const val ORGANIZATION = "organizations"
    const val TAGS = "tags"
    const val SEARCH_COMMENTS = "search_comments"
}
